server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf8
    username: myadmin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml      # mapper.xml 파일 위치
  #type-aliases-package: board.mybatis.dto.**



